/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestVersionChooserDialog.java
 *
 * Created on Mar 14, 2011, 10:42:42 PM
 */

package edu.uwm.cs.molhado.version;

import edu.cmu.cs.fluid.version.Version;

/**
 *
 * @author chengt
 */
public class TestVersionChooserDialog extends javax.swing.JFrame{

    /** Creates new form TestVersionChooserDialog */
    public TestVersionChooserDialog(java.awt.Frame parent, boolean modal) {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jButton1 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jButton1.setText(org.openide.util.NbBundle.getMessage(TestVersionChooserDialog.class, "TestVersionChooserDialog.jButton1.text")); // NOI18N
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jButton1)
        .addContainerGap(324, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jButton1)
        .addContainerGap(261, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

		private Version createVersionTree(){
			Version.setVersion(Version.getInitialVersion());
			Version.bumpVersion();
			Version v10 = VersionSupport.commit("1.0", "1.0");
			Version.bumpVersion();
			Version v20 = VersionSupport.commit("2.0", "2.0");
			Version.bumpVersion();
			Version v30 = VersionSupport.commit("3.0", "3.0");
			Version.setVersion(v20);
			Version.bumpVersion();;
		  Version v31 = VersionSupport.commitAsBranch("3.1", "3.1");
			return v10;
		}

		private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

			VersionChooserDialog chooser = new VersionChooserDialog(createVersionTree(), this);
			chooser.setVisible(true);
			if ( chooser.RET_OK == chooser.getReturnStatus()){
				System.out.println("You have chosen version: " + chooser.getSelectedVersion());
			} else {
				System.out.println("You have canceled version selection");
			}
		}//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TestVersionChooserDialog dialog = new TestVersionChooserDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  // End of variables declaration//GEN-END:variables

}
