/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * VersionChooserDialog.java
 *
 * Created on Mar 14, 2011, 10:37:46 PM
 */
package edu.uwm.cs.molhado.version;

import edu.cmu.cs.fluid.version.Version;
import edu.uwm.cs.molhado.component.Project;
import java.awt.Frame;
import java.util.Collection;
import javax.swing.JComponent;
import javax.swing.JFrame;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;

/**
 *
 * @author chengt
 */
public class VersionGraphViewer extends javax.swing.JDialog {

	private VersionGraphScene scene;

	private int returnStatus = RET_CANCEL;

	/** A return status code - returned if Cancel button has been pressed */
	public static final int RET_CANCEL = 0;
	/** A return status code - returned if OK button has been pressed */
	public static final int RET_OK = 1;

	/** Creates new form VersionChooserDialog */
	public VersionGraphViewer(Project project, Frame parent) {
		super(parent, false);
		setTitle(project.getName());
		initComponents();
		this.setLocationRelativeTo(parent);
		scene = new VersionGraphScene(project.getInitialVersion());
		JComponent component = scene.createView(); //must be called before build graph
		jScrollPane1.setViewportView(component); //must be called before build graph
		scene.buildGraph();  //must to be called last..
		//scene.validate();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jButton1 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jScrollPane1.setBorder(null);

    jButton1.setText(org.openide.util.NbBundle.getMessage(VersionGraphViewer.class, "VersionGraphViewer.jButton1.text")); // NOI18N
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(174, Short.MAX_VALUE)
        .addComponent(jButton1)
        .addContainerGap())
      .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton1)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
		doClose(0);
	}//GEN-LAST:event_jButton1ActionPerformed


	//public Lookup getLookup() {
	//	return scene.getLookup();
	//}

	private void doClose(int retStatus) {
		returnStatus = retStatus;
		setVisible(false);
		dispose();
	}


		private static Version createVersionTree() {
		Version.setVersion(Version.getInitialVersion());
		Version.bumpVersion();
		Version v10 = VersionSupport.commit("1.0", "1.0");
		Version.bumpVersion();
		Version v20 = VersionSupport.commit("2.0", "2.0");
		Version.bumpVersion();
		Version v30 = VersionSupport.commit("3.0", "3.0");
		Version.setVersion(v20);
		Version.bumpVersion();
		Version v31 = VersionSupport.commitAsBranch("3.1", "3.1");
		return v10;
	}

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JScrollPane jScrollPane1;
  // End of variables declaration//GEN-END:variables
}
