package edu.uwm.cs.gpl.graph;

public enum Algorithms {
	VERTEX_NUMBERING,
	CONNECTED_COMPONENTS,
	STRONGLY_CONNECTED_COMPONENTS,
	CYCLE_CHECKING,
	MST_PRIM,
	MST_KRUSKAL,
	SINGLE_SHORTEST_PATH
}